/*
Deployment script for Machine_Database

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Machine_Database"
:setvar DefaultFilePrefix "Machine_Database"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The type for column Date_Acquired in table [dbo].[General_Table] is currently  NVARCHAR (50) NULL but is being changed to  VARCHAR (50) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (50) NULL.

The type for column Donated_Or_Loaned in table [dbo].[General_Table] is currently  NCHAR (10) NULL but is being changed to  VARCHAR (10) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (10) NULL.

The type for column Horse_Power in table [dbo].[General_Table] is currently  NCHAR (50) NULL but is being changed to  VARCHAR (50) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (50) NULL.

The type for column Link_to_TractorData in table [dbo].[General_Table] is currently  NVARCHAR (MAX) NULL but is being changed to  VARCHAR (MAX) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (MAX) NULL.

The type for column Machine_Location in table [dbo].[General_Table] is currently  NCHAR (50) NULL but is being changed to  VARCHAR (50) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (50) NULL.

The type for column Machine_Type in table [dbo].[General_Table] is currently  NCHAR (25) NULL but is being changed to  VARCHAR (50) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (50) NULL.

The type for column Model in table [dbo].[General_Table] is currently  NCHAR (25) NULL but is being changed to  VARCHAR (25) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (25) NULL.

The type for column Original_Owner in table [dbo].[General_Table] is currently  NCHAR (100) NULL but is being changed to  VARCHAR (100) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (100) NULL.

The type for column Restoration_Status in table [dbo].[General_Table] is currently  NCHAR (50) NULL but is being changed to  VARCHAR (50) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (50) NULL.

The type for column Year_Built in table [dbo].[General_Table] is currently  NCHAR (10) NULL but is being changed to  VARCHAR (10) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (10) NULL.
*/

IF EXISTS (select top 1 1 from [dbo].[General_Table])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Starting rebuilding table [dbo].[General_Table]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_General_Table] (
    [Id]                      INT           IDENTITY (1, 1) NOT NULL,
    [Machine_Type]            VARCHAR (50)  NULL,
    [Year_Built]              VARCHAR (10)  NULL,
    [Original_Owner]          VARCHAR (100) NULL,
    [Date_Acquired]           VARCHAR (50)  NULL,
    [Description]             VARCHAR (MAX) NULL,
    [Image]                   IMAGE         NULL,
    [Maintenence_Information] VARCHAR (MAX) NULL,
    [Model]                   VARCHAR (25)  NULL,
    [Horse_Power]             VARCHAR (50)  NULL,
    [Machine_Location]        VARCHAR (50)  NULL,
    [Restoration_Status]      VARCHAR (50)  NULL,
    [Link_to_TractorData]     VARCHAR (MAX) NULL,
    [Donated_Or_Loaned]       VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[General_Table])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_General_Table] ON;
        INSERT INTO [dbo].[tmp_ms_xx_General_Table] ([Id], [Machine_Type], [Year_Built], [Original_Owner], [Date_Acquired], [Description], [Image], [Maintenence_Information], [Model], [Horse_Power], [Machine_Location], [Restoration_Status], [Link_to_TractorData], [Donated_Or_Loaned])
        SELECT   [Id],
                 [Machine_Type],
                 [Year_Built],
                 [Original_Owner],
                 [Date_Acquired],
                 [Description],
                 [Image],
                 [Maintenence_Information],
                 [Model],
                 [Horse_Power],
                 [Machine_Location],
                 [Restoration_Status],
                 [Link_to_TractorData],
                 [Donated_Or_Loaned]
        FROM     [dbo].[General_Table]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_General_Table] OFF;
    END

DROP TABLE [dbo].[General_Table];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_General_Table]', N'General_Table';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO
