/*
Deployment script for Machine_Database_Fixed

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Machine_Database_Fixed"
:setvar DefaultFilePrefix "Machine_Database_Fixed"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Rename refactoring operation with key 9719587c-4140-427f-8306-81f8f941d3f1, fb9e9e2e-f168-4965-9149-b185ff25e136 is skipped, element [dbo].[General Table].[MachineName] (SqlSimpleColumn) will not be renamed to Machine Type';


GO
PRINT N'Rename refactoring operation with key d6173efe-3aaf-48a7-9c78-6b4cff46122e is skipped, element [dbo].[General Table].[YearBuilt] (SqlSimpleColumn) will not be renamed to Year Built';


GO
PRINT N'Rename refactoring operation with key 4c1599cb-8511-4156-bdb2-cf30f699493d, 8639df6d-1e7c-46dd-8829-ef1fb7bf119c is skipped, element [dbo].[General Table].[DonatedBy] (SqlSimpleColumn) will not be renamed to Original Owner';


GO
PRINT N'Rename refactoring operation with key af7bfda1-769e-4d69-a07e-b068950ede35, 9499ebc9-47b8-4253-95dc-9ccf27acf556 is skipped, element [dbo].[General Table].[DonationDate] (SqlSimpleColumn) will not be renamed to Data Acquired';


GO
PRINT N'Rename refactoring operation with key 14f48eb2-9b56-4782-98fb-37340e8e585b is skipped, element [dbo].[General Table].[Maintanece Information] (SqlSimpleColumn) will not be renamed to Maintenence Information';


GO
PRINT N'Rename refactoring operation with key 5e369b1d-ce67-43b4-88da-df44458772cc is skipped, element [dbo].[General_Table].[Maintenence Information] (SqlSimpleColumn) will not be renamed to Maintenence_Information';


GO
PRINT N'Rename refactoring operation with key fd2f6696-bf56-4d01-91a5-97abf227330c is skipped, element [dbo].[General_Table].[Machine Location] (SqlSimpleColumn) will not be renamed to Machine_Location';


GO
PRINT N'Rename refactoring operation with key 37e64cfe-3231-4a2d-a9c9-2de11a08e3c6 is skipped, element [dbo].[General_Table].[Second_Image] (SqlSimpleColumn) will not be renamed to SecondImage';


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9719587c-4140-427f-8306-81f8f941d3f1')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9719587c-4140-427f-8306-81f8f941d3f1')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd6173efe-3aaf-48a7-9c78-6b4cff46122e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d6173efe-3aaf-48a7-9c78-6b4cff46122e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4c1599cb-8511-4156-bdb2-cf30f699493d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4c1599cb-8511-4156-bdb2-cf30f699493d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'af7bfda1-769e-4d69-a07e-b068950ede35')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('af7bfda1-769e-4d69-a07e-b068950ede35')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '14f48eb2-9b56-4782-98fb-37340e8e585b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('14f48eb2-9b56-4782-98fb-37340e8e585b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'fb9e9e2e-f168-4965-9149-b185ff25e136')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('fb9e9e2e-f168-4965-9149-b185ff25e136')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8639df6d-1e7c-46dd-8829-ef1fb7bf119c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8639df6d-1e7c-46dd-8829-ef1fb7bf119c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9499ebc9-47b8-4253-95dc-9ccf27acf556')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9499ebc9-47b8-4253-95dc-9ccf27acf556')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5e369b1d-ce67-43b4-88da-df44458772cc')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5e369b1d-ce67-43b4-88da-df44458772cc')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'fd2f6696-bf56-4d01-91a5-97abf227330c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('fd2f6696-bf56-4d01-91a5-97abf227330c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '37e64cfe-3231-4a2d-a9c9-2de11a08e3c6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('37e64cfe-3231-4a2d-a9c9-2de11a08e3c6')

GO

GO
PRINT N'Update complete.';


GO
